spring:
  thymeleaf:
    cache: false
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  tomcat:
    access_log_enabled: true
    basedir: target/tomcat